# Site settings
title: el blog del Eme
email: eme@devf.mx
description: > # this means to ignore newlines until "baseurl:"
  El más reciente blog del Eme. Escribo sobre lo que pienso, y pienso mucho en madres geeks como tecnología, economía, activismo, educación, política, etc. Todas las opiniones compartidas en este medio son 100% mías.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ememorato
github_username:  ememorato

# Build settings
markdown: kramdown
